CATEGORIES = [
    "T-Shirts",
    "Jeans",
    "Hoodies",
    "Shirts",
    "Dresses",
    "Jackets",
    "Shorts",
    "Sweaters",
    "Pants",
    "Polo",
]

PRODUCTS = [
    {
        "name": "Classic Cotton T-Shirt (Product A)",
        "model": "CT-2024",
        "serial_number": "CT2024001",
        "description": "Premium cotton t-shirt with a comfortable fit. Perfect for everyday wear.",
        "price": 29.99,
        "stock": 50,
        "category": "T-Shirts",
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
        "rating": 4.5,
        "warranty_status": "6 months",
        "distributor": "Fashion Co.",
    },
    {
        "name": "Slim Fit Denim Jeans (Product B)",
        "model": "DJ-2024",
        "serial_number": "DJ2024002",
        "description": "Modern slim fit jeans with stretch denim for maximum comfort.",
        "price": 79.99,
        "stock": 3,
        "category": "Jeans",
        "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
        "rating": 4.8,
        "warranty_status": "1 year",
        "distributor": "Denim World",
    },
    {
        "name": "Casual Hoodie (Product C)",
        "model": "CH-2024",
        "serial_number": "CH2024003",
        "description": "Cozy fleece hoodie with adjustable drawstring and kangaroo pocket.",
        "price": 54.99,
        "stock": 50,
        "category": "Hoodies",
        "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400",
        "rating": 4.3,
        "warranty_status": "6 months",
        "distributor": "Comfort Wear",
    },
    {
        "name": "Formal Dress Shirt",
        "model": "FS-2024",
        "serial_number": "FS2024004",
        "description": "Elegant dress shirt perfect for business or formal occasions.",
        "price": 64.99,
        "stock": 25,
        "category": "Shirts",
        "image": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400",
        "rating": 4.6,
        "warranty_status": "6 months",
        "distributor": "Elite Fashion",
    },
    {
        "name": "Summer Floral Dress",
        "model": "SD-2024",
        "serial_number": "SD2024005",
        "description": "Light and breezy floral dress perfect for summer days.",
        "price": 89.99,
        "stock": 18,
        "category": "Dresses",
        "image": "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
        "rating": 4.7,
        "warranty_status": "3 months",
        "distributor": "Summer Collection",
    },
    {
        "name": "Leather Jacket",
        "model": "LJ-2024",
        "serial_number": "LJ2024006",
        "description": "Premium leather jacket with modern styling and durable construction.",
        "price": 199.99,
        "stock": 12,
        "category": "Jackets",
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        "rating": 4.9,
        "warranty_status": "2 years",
        "distributor": "Leather Luxury",
    },
    {
        "name": "Athletic Shorts",
        "model": "AS-2024",
        "serial_number": "AS2024007",
        "description": "Breathable athletic shorts with moisture-wicking technology.",
        "price": 34.99,
        "stock": 50,
        "category": "Shorts",
        "image": "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400",
        "rating": 4.4,
        "warranty_status": "6 months",
        "distributor": "Sports Pro",
    },
    {
        "name": "Wool Blend Sweater",
        "model": "WS-2024",
        "serial_number": "WS2024008",
        "description": "Warm and stylish wool blend sweater for cold weather.",
        "price": 74.99,
        "stock": 22,
        "category": "Sweaters",
        "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
        "rating": 4.5,
        "warranty_status": "1 year",
        "distributor": "Winter Warmth",
    },
    {
        "name": "Cargo Pants",
        "model": "CP-2024",
        "serial_number": "CP2024009",
        "description": "Versatile cargo pants with multiple pockets and durable fabric.",
        "price": 69.99,
        "stock": 35,
        "category": "Pants",
        "image": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400",
        "rating": 4.2,
        "warranty_status": "1 year",
        "distributor": "Urban Style",
    },
    {
        "name": "Casual Polo Shirt",
        "model": "PS-2024",
        "serial_number": "PS2024010",
        "description": "Classic polo shirt combining comfort with timeless style.",
        "price": 44.99,
        "stock": 40,
        "category": "Polo",
        "image": "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400",
        "rating": 4.6,
        "warranty_status": "6 months",
        "distributor": "Classic Wear",
    },
    {
        "name": "Printed Graphic Tee",
        "model": "GT-2024",
        "serial_number": "GT2024011",
        "description": "Trendy graphic tee with unique prints and soft cotton fabric.",
        "price": 32.99,
        "stock": 0,
        "category": "T-Shirts",
        "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400",
        "rating": 4.3,
        "warranty_status": "3 months",
        "distributor": "Fashion Co.",
    },
    {
        "name": "Chino Trousers",
        "model": "CT-2024",
        "serial_number": "CT2024012",
        "description": "Smart casual chino trousers suitable for work and weekends.",
        "price": 59.99,
        "stock": 28,
        "category": "Pants",
        "image": "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400",
        "rating": 4.7,
        "warranty_status": "1 year",
        "distributor": "Smart Casual",
    },
    {
        "name": "Designer Blazer (Product D)",
        "model": "DB-2024",
        "serial_number": "DB2024013",
        "description": "Elegant designer blazer perfect for professional occasions.",
        "price": 149.99,
        "stock": 15,
        "category": "Jackets",
        "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400",
        "rating": 4.8,
        "warranty_status": "1 year",
        "distributor": "Premium Fashion",
    },
    {
        "name": "Running Shoes (Product E)",
        "model": "RS-2024",
        "serial_number": "RS2024014",
        "description": "High-performance running shoes with advanced cushioning.",
        "price": 119.99,
        "stock": 30,
        "category": "Shorts",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "rating": 4.9,
        "warranty_status": "6 months",
        "distributor": "Athletic Pro",
    },
    {
        "name": "Vintage Denim Jacket (Product F)",
        "model": "VJ-2024",
        "serial_number": "VJ2024015",
        "description": "Classic vintage denim jacket with timeless appeal.",
        "price": 89.99,
        "stock": 20,
        "category": "Jackets",
        "image": "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400",
        "rating": 4.6,
        "warranty_status": "1 year",
        "distributor": "Vintage Collection",
    },
]